const ROUTES = {
  ROOT: "/",
  LOGIN: "/login",
  RESET_PASSWORD: "/reset-password",
  UPDATE_PASSWORD: `/updatePassword/:token`,
  DASHBOARD: "/dashboard",
  EMPLOYEES: "/employees",
  TASKS: "/tasks",
  LEAVE_MANAGEMENT: "/leaves",
  FINANCE: "/finance",
  REIMBURSEMENTS: "/reimbursements",
  RESIGNATIONS: "resignations",
  PAYROLL: "/payroll",
  ATTENDENCE: "/attendence",
  ATTENDENCE_VIEW:"/attendence-view",
  DOCUMENTS: "/documents",
  ORG_CHART: "/org-chart",
  SETTINGS: "/settings",
  OFFER_LETTERS: "/offer-letters",
  ANNOUNCEMENTS: "/announcements",
  AUDIT_LOGS:"/audit-logs",
  UNAUTHORIZED: "/unauthorized",
};

export default ROUTES;
